GymApp/GymApp.Web/Models/Course.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GymApp.Web.Models {
    public class Course : BaseEntity {
        [Key]
        public int Id { get; set; }

        [Required]
        public int TrainerId { get; set; }
        [ForeignKey("TrainerId")]
        public virtual Trainer? Trainer { get; set; }

        [Required]
        public int CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        public virtual Category? Category { get; set; }

        public DateTime StartTime { get; set; }
        
        public DateTime EndTime { get; set; }

        public int UserCount { get; set; }

    }
}

GymApp/GymApp.Web/Areas/Management/Controllers/CourseController.cs
using GymApp.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GymApp.Web.Areas.Management.Controllers
{
	public class CourseController : Controller
	{
		GymDbContext db = new GymDbContext();
		// GET: CourseController
		public ActionResult Index()
		{
			var courses = db.Courses
			.Where(c => c.Deleted == false)
			.Include("Trainer").Include("Category")
			.ToList();
			return View(courses);
		}

		// GET: CourseController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: CourseController/Create
		public ActionResult Create()
		{
			ViewBag.TrainerId = new SelectList(db.Trainers
				.Where(x => x.Deleted == false && x.Status), "Id", "FullName", null);
			ViewBag.CategoryId = new SelectList(db.Categories
				.Where(x => x.Deleted == false && x.Status), "Id", "Title", null);

			//herhangi bir seçili eleman olmaıgı icin trainerda
			//hangi modeli seçmesini istediğimizde bir liste yapıp veriyi taşıyor 

			return View();
		}

		// POST: CourseController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(Course model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					model.Status = true;
					model.Deleted = false;
					model.CreatedDate = DateTime.Now;
					model.CreatedBy = 0;
					db.Courses.Add(model);
					db.SaveChanges();
					return RedirectToAction(nameof(Index));
				}


				ViewBag.TrainerId = new SelectList(db.Trainers
					.Where(x => x.Deleted == false && x.Status), "Id", "FullName", model.TrainerId);
				ViewBag.CategoryId = new SelectList(db.Categories
					.Where(x => x.Deleted == false && x.Status), "Id", "Title", model.CategoryId);
				return View(model);
			}
			catch
			{

				return View(model);
			}
		}

		// GET: CourseController/Edit/5
		public ActionResult Edit(int id)
		{
			var course = db.Courses.Find(id);

			if (course == null)
			{
				return RedirectToAction(nameof(Index));
			}
			ViewBag.TrainerId = new SelectList(db.Trainers
				.Where(x => x.Deleted == false && x.Status), "Id", "FullName", course.TrainerId);
			ViewBag.CategoryId = new SelectList(db.Categories
				.Where(x => x.Deleted == false && x.Status), "Id", "Title", course.CategoryId);
			return View(course);
		}

		// POST: CourseController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Course model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var editCourse = db.Courses.Find(model.Id);


					if (editCourse == null)
					{
						return View(model);
					}
					editCourse.TrainerId = model.TrainerId;
					editCourse.CategoryId = model.CategoryId;
					editCourse.StartTime = model.StartTime;
					editCourse.EndTime = model.EndTime;
					editCourse.UserCount = model.UserCount;
					editCourse.Status = model.Status;
					editCourse.UpdatedBy = 0;
					editCourse.UpdatedDate = DateTime.Now;
					db.SaveChanges();
					return RedirectToAction(nameof(Index));
				}
				ViewBag.TrainerId = new SelectList(db.Trainers
				.Where(x => x.Deleted == false && x.Status), "Id", "FullName", model.TrainerId);
				ViewBag.CategoryId = new SelectList(db.Categories
					.Where(x => x.Deleted == false && x.Status), "Id", "Title", model.CategoryId);
				//yukarıdaki hazır kurs ve eğitmenleri gösteren şey
				return View(model);
			}
			catch
			{
				return View(model);
			}
		}

		// GET: CourseController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: CourseController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

GymApp/GymApp.Web/Areas/Management/Views/Course/Create.cshtml
@model Course

<div class="row">
	<div class="col-12">
		<div class="card border-top border-0 border-4 border-dark">
			<div class="card-body p-5">
				<div class="card-title text-center">
					<i class="bx bxs-user-circle text-dark font-50"></i>
					<h5 class="mb-5 mt-2 text-dark">Course Ekle</h5>
				</div>
				<hr>
				<form class="row g-3" method="post">
					<div class="col-12">
						<label asp-for="TrainerId" class="form-label">Eğitmen</label>
						<div class="input-group input-group-lg">
							<select asp-for="TrainerId" asp-items="@ViewBag.TrainerId" class="form-control"></select>
							<span class="text-danger" asp-validation-for="TrainerId"></span>
						</div>
					</div>
					<div class="col-12">
						<label asp-for="CategoryId" class="form-label">Kategori</label>
						<div class="input-group input-group-lg">
							<select asp-for="CategoryId" asp-items="@ViewBag.CategoryId" class="form-control"></select>
							<span class="text-danger" asp-validation-for="CategoryId"></span>
						</div>
					</div>
					<div class="col-12">
						<label asp-for="StartTime" class="form-label">Başlangıç</label>
						<div class="input-group input-group-lg">
							<input type="datetime-local" class="form-control border-start-0" asp-for="StartTime" placeholder="Başlangıç">

							<span class="text-danger" asp-validation-for="StartTime"></span>
						</div>
					</div>
					<div class="col-12">
						<label asp-for="EndTime" class="form-label">Bitiş</label>
						<div class="input-group input-group-lg">
							<input type="datetime-local" class="form-control border-start-0" asp-for="EndTime" placeholder="Bitiş">

							<span class="text-danger" asp-validation-for="EndTime"></span>
						</div>
					</div>
					<div class="col-12">
						<label asp-for="UserCount" class="form-label">Üye Sayısı</label>
						<div class="input-group input-group-lg">
							<input type="text" class="form-control border-start-0" asp-for="UserCount" placeholder="Kapasite">

							<span class="text-danger" asp-validation-for="UserCount"></span>

						</div>
					</div>
					<div class="col-12">
						<div class="d-grid">
							<button type="submit" class="btn btn-dark btn-lg px-5"><i class="bx bxs-lock-open"></i>Kaydet</button>
						</div>
					</div>
					<hr>
				</form>
			</div>
		</div>
	</div>
</div>

GymApp/GymApp.Web/Areas/Management/Views/Course/Edit.cshtml
@model Course

<div class="row">
	<div class="col-12">
		<div class="card border-top border-0 border-4 border-dark">
			<div class="card-body p-5">
				<div class="card-TrainerId text-center">
					<i class="bx bxs-user-circle text-dark font-50"></i>
					<h5 class="mb-5 mt-2 text-dark">Kurs Düzenle</h5>
				</div>
				<hr>
				<form class="row g-3" method="post">
					<input type="hidden" asp-for="Id" />
					<div class="col-12">
						<label asp-for="TrainerId" class="form-label">Eğitmen</label>
						<div class="input-group input-group-lg">
							<select asp-for="TrainerId" asp-items="@ViewBag.TrainerId" class="form-control"></select>
							<span class="text-danger" asp-validation-for="TrainerId"></span>
						</div>
					</div>
					<div class="col-12">
						<label asp-for="CategoryId" class="form-label">Kategori</label>
						<div class="input-group input-group-lg">
							<select asp-for="CategoryId" asp-items="@ViewBag.CategoryId" class="form-control"></select>
							<span class="text-danger" asp-validation-for="CategoryId"></span>
						</div>
					</div>
					<div class="col-12">
						<label asp-for="StartTime" class="form-label">Başlangıç</label>
						<div class="input-group input-group-lg">
							<input type="datetime-local" class="form-control border-start-0" asp-for="StartTime" placeholder="Başlangıç">

							<span class="text-danger" asp-validation-for="StartTime"></span>
						</div>
					</div>
					<div class="col-12">
						<label asp-for="EndTime" class="form-label">Bitiş</label>
						<div class="input-group input-group-lg">
							<input type="datetime-local" class="form-control border-start-0" asp-for="EndTime" placeholder="Bitiş">

							<span class="text-danger" asp-validation-for="EndTime"></span>
						</div>
					</div>
					<div class="col-12">
						<label asp-for="UserCount" class="form-label">Üye Sayısı</label>
						<div class="input-group input-group-lg">
							<input type="text" class="form-control border-start-0" asp-for="UserCount" placeholder="Kapasite">

							<span class="text-danger" asp-validation-for="UserCount"></span>

						</div>
					</div>
					<div class="col-12">
						<label asp-for="Status" class="form-label">Durumu</label>
						<select class="form-select mb-3" asp-for="Status">
							<option value="true">Aktif</option>
							<option value="false">Pasif</option>
						</select>
					</div>

					<div class="col-12">
						<div class="d-grid">
							<button type="submit" class="btn btn-dark btn-lg px-5"><i class="bx bxs-lock-open"></i>Kaydet</button>
						</div>
					</div>
					<hr>
				</form>
			</div>
		</div>
	</div>
</div>

GymApp/GymApp.Web/Areas/Management/Views/Course/Index.cshtml
@model IEnumerable<Course>

<a class="btn btn-success"
   asp-area="Management"
   asp-controller="Course"
   asp-action="Create">Ekle</a>

<div class="card radius-15">
	<div class="card-body">
		<div class="card-title">
			<h4 class="mb-0">Kategori</h4>
		</div>
		<hr>
		<div class="table-responsive">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th scope="col">Kategori</th>
						<th scope="col">Eğitmen</th>
						<th scope="col">Başlangıç</th>
						<th scope="col">Bitiş</th>
						<th scope="col">Üye Sayısı</th>
						<th scope="col">Durumu</th>
						<th scope="col">#</th>

					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							<td>
								@item.Category.Title
							</td>
							<td>
								@item.Trainer.FullName
							</td>
							<td>
								@item.StartTime
							</td>
							<td>
								@item.EndTime
							</td>
							<td>
								@item.UserCount
							</td>

							<td>
								@if (@item.Status)
								{
									<span>Aktif</span>
								}
								else
								{
									<span>Pasif</span>
								}
							</td>
							<td>
								<a class="btn btn-primary"
								   asp-area="Management"
								   asp-controller="Course"
								   asp-action="Details"
								   asp-route-id="@item.Id">Detay</a>
								<a class="btn btn-primary"
								   asp-area="Management"
								   asp-controller="Course"
								   asp-action="Edit"
								   asp-route-id="@item.Id">Düzenle</a>
								<a class="btn btn-danger"
								   asp-area="Management"
								   asp-controller="Course"
								   asp-action="Delete"
								   asp-route-id="@item.Id">Sil</a>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>