GymApp/GymApp.Web/Controllers/MemberController.cs
using GymApp.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace GymApp.Web.Controllers
{
    public class MemberController : Controller
    {
        GymDbContext db = new GymDbContext();   
        public IActionResult Index()
        {
            // kayıt formu
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(User model) {

            //todo: kayıt formu
            //todo: kullanıcı üyeliği alınacak
            return View();
        }

        public IActionResult Pricing(){
            var pricing = db.Pricings
                .Where(c => c.Status && c.Deleted == false).ToList();
            return View();  
        }
    }
}

GymApp/GymApp.Web/Views/Shared/_Footer.cshtml
<section class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="footer__about">
                    <img src="img/footer-logo.png" alt="">
                    <ul>
                        <li><i class="fa fa-clock-o"></i> Mon - Fri: 6:30am - 07:45pm</li>
                        <li><i class="fa fa-clock-o"></i> Sat - Sun: 8:30am - 05:45pm</li>
                    </ul>
                    <form action="#" class="subscribe-form">
                        <input type="text" placeholder="Your Email">
                        <button type="submit"><i class="fa fa-send"></i></button>
                    </form>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h5>Inspiration</h5>
                    <ul>
                        <li><a href="#">Online Pilates</a></li>
                        <li><a href="#">Yoga for Beginners</a></li>
                        <li><a href="#">Online Pilates</a></li>
                        <li><a href="#">Online Yoga</a></li>
                        <li><a href="#">Conditioning</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h5>About Us</h5>
                    <ul>
                        <li><a href="#">Our Vision</a></li>
                        <li><a href="#">Our Mission</a></li>
                        <li><a href="#">Meet The Team</a></li>
                        <li><a href="#">Introduce</a></li>
                        <li><a href="#">Customer Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h5>Contact Us</h5>
                    <ul class="footer-address">
                        <li><i class="fa fa-phone"></i> (01) 436 8888</li>
                        <li><i class="fa fa-envelope"></i> hello@zogin.com</li>
                        <li><i class="fa fa-location-arrow"></i> 828 Granville Lights Suite 466</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer__copyright">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <div class="footer__copyright__text">
                        <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
                    </div>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="footer__copyright__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

GymApp/GymApp.Web/Views/Shared/_Head.cshtml
<meta charset="UTF-8">
<meta name="description" content="Directing Template">
<meta name="keywords" content="Directing, unica, creative, html">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Zogin | Template</title>

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">

<!-- Css Styles -->
<link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
<link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
<link rel="stylesheet" href="~/css/barfiller.css" type="text/css">
<link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
<link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
<link rel="stylesheet" href="~/css/style.css" type="text/css">

GymApp/GymApp.Web/Views/Shared/_Header.cshtml
  <!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="header__logo">
                        <a href="./index.html"><img src="~/img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-9 col-md-9">
                    <div class="header__top__widget">
                        <ul>
                            <li>CALL US: + 1 800-567-8990</li>
                            <li>WRITE US: OFFICE@EXAMPLE.COM</li>
                            <li>OPENING TIMES: MON - FRI: 9:00 - 19:00</li>
                        </ul>
                        <a href="#" class="primary-btn">JOIN US</a>
                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </div>
    <div class="header__nav">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-9">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                            <li><a asp-controller="Home" asp-action="About">Hakkımızda</a></li>
                            <li><a asp-controller="Lecture" asp-action="Index">Kurslar</a></li>
                            <li><a asp-controller="Lecture" asp-action="Trainer">Eğitmenler</a></li>
                            <li><a asp-controller="Home" asp-action="Contact">İletişim</a></li>
                            <li><a asp-controller="Member" asp-action="Index">Üyelik</a></li>
                            <li><a asp-controller="Member" asp-action="Pricing">Paketler</a></li>

                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3 col-md-3">
                    <div class="header__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Header Section End -->

GymApp/GymApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">
<head>
    <partial name="_Head" />
</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <partial name="_Menu" />
    <partial name="_Header" />
    @RenderBody()
    <partial name="_Footer" />
    <partial name="_Script" />
</body>

</html>

GymApp/GymApp.Web/Views/Shared/_Menu.cshtml
  <!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu">
    <div class="offcanvas__logo">
        <a href="./index.html"><img src="~/img/logo.png" alt=""></a>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__widget">
        <ul>
            <li>CALL US: + 1 800-567-8990</li>
            <li>WRITE US: OFFICE@EXAMPLE.COM</li>
            <li>OPENING TIMES: MON - FRI: 9:00 - 19:00</li>
        </ul>
        <a href="#" class="primary-btn">JOIN US</a>
    </div>
    <nav class="header__menu">
        <ul class="mobile-menu">
            <li class="active"><a href="./index.html">Home</a></li>
            <li><a href="./about-us.html">About</a></li>
            <li><a href="./classes.html">Classes</a></li>
            <li>
                <a href="#">Pages</a>
                <ul class="dropdown">
                    <li><a href="./classes-details.html">Classes Details</a></li>
                    <li><a href="./blog-details.html">Blog Details</a></li>
                    <li><a href="./pricing.html">Pricing</a></li>
                    <li><a href="./faq.html">Faq</a></li>
                </ul>
            </li>
            <li><a href="./blog.html">Blog</a></li>
            <li><a href="./contact.html">Contact</a></li>
        </ul>
    </nav>
    <div class="offcanvas__social">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
    </div>
</div>
<!-- Offcanvas Menu End -->

GymApp/GymApp.Web/Views/Shared/_Script.cshtml
<script src="~/js/jquery-3.3.1.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/jquery.nice-select.min.js"></script>
<script src="~/js/jquery.barfiller.js"></script>
<script src="~/js/jquery.slicknav.js"></script>
<script src="~/js/owl.carousel.min.js"></script>
<script src="~/js/main.js"></script>